language: go
go_import_path: github.com/33cn/plugin
os: linux
dist: xenial

notifications:
  email: false
jobs:
  include:
    - stage: check_fmt
      sudo: require
      go: "1.9.x"
      install:
        - go get -u golang.org/x/tools/cmd/goimports
#        - go get -u gopkg.in/alecthomas/gometalinter.v2
#        - gometalinter.v2 -i
        - go get -u mvdan.cc/sh/cmd/shfmt
        - go get -u mvdan.cc/sh/cmd/gosh
      script:
        - make fmt_go
        - "./build/travis_auto_ci.sh"
#        - make fmt_go
#        - make checkgofmt && make fmt_go
#        - make linter

#    - stage: unit-test
#      go: "1.9.x"
#      install: skip
#      script:
#        - make test

#    - stage: coverage
#      if: branch = master
#      go: "1.9.x"
#      before_install:
#        - go get -t -v ./...
#      install: skip
#      script:
#        - make coverage
#      after_success:
#        - bash <(curl -s https://codecov.io/bash)


#    - stage: deploy
#      sudo: required
#      services:
#        - docker
#      env:
#        - DOCKER_COMPOSE_VERSION=1.21.2
#      install:
#        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#        - sudo apt-get update
#        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#        - sudo rm /usr/local/bin/docker-compose
#        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#        - chmod +x docker-compose
#        - sudo mv docker-compose /usr/local/bin
#      before_script: make build_ci
#      script:
##        - make docker-compose && make docker-compose-down && make docker-compose DAPP=paracross && make docker-compose-down DAPP=paracross && make docker-compose DAPP=relay && make docker-compose-down DAPP=relay
#        - make docker-compose DAPP=all && make docker-compose-down DAPP=all && make clean
#env:
  global:
    secure: edvumnefzvrhdi+wHdE3FkKMghDC0n8IyA6pTU1b2o9COlGFmbDv7A2LNVPagrATAwh9iLWmh6VD7fErHHActOpwi5LkszXci+nM/YsyUgqibdteUCP97dxSILvS3LFI/6bHwWfjPcjYEuykPXLPt9db1i4O3lB4vnQ/nlekb36G+75tfXOXTLDZFgYGLXypQT1mKrnKTqRtmbRq001OQGkypur+mHZmrN4B2gEvbKc2kONdfGvxcp6uOMQyojpgaVDwEw8NKLMDFYWlU6FnYtmc7aiwyDfN8czzv3nicHEs9z2GHvk7l0rD0zE7kj2mxIES90qfc97zbppqxzDlJMMjnUDaQLdhAjyMxrWkjyTeMRRGUNzJqXa+LuiFjWwUlvQMAJttqwWBv832gT6ayCfFtINNwGkECI+lC4IKCt542JdG5ncfyI38Sy1YhMmjVE93trbvUCkd9jy30x3/5Wdqmuq/09gOObdLPrDYiqXPmwgeYRqp4Gz+Q1lVFzFZd/gElRLc4NDenICgNZCVCEBQhIdYhWwc4rM/1/Gag249PSLOXILyEAQg9aLS1jmyS9LKF1AbcnuE2b7/1r4iWtD1d97aj/zH+/SxCCHX0UUwgzA6kIvh90rLAwEEO1/idd2S9+TKqDpKt++lGUIIsFDieJdYZR+Phr1j4fS3xKg=
