language: go
go_import_path: github.com/33cn/plugin
os: linux
dist: xenial
notifications:
  email: false
jobs:
  include:
    - stage: check_fmt
      sudo: require
      go: "1.9.x"
      install:
        - go get -u golang.org/x/tools/cmd/goimports
#        - go get -u gopkg.in/alecthomas/gometalinter.v2
#        - gometalinter.v2 -i
        - go get -u mvdan.cc/sh/cmd/shfmt
        - go get -u mvdan.cc/sh/cmd/gosh
      script:
        - make fmt_go
      after_success:
      - "./build/travis_auto_ci.sh"
#        - make fmt_go
#        - make checkgofmt && make fmt_go
#        - make linter

#    - stage: unit-test
#      go: "1.9.x"
#      install: skip
#      script:
#        - make test

#    - stage: coverage
#      if: branch = master
#      go: "1.9.x"
#      before_install:
#        - go get -t -v ./...
#      install: skip
#      script:
#        - make coverage
#      after_success:
#        - bash <(curl -s https://codecov.io/bash)


#    - stage: deploy
#      sudo: required
#      services:
#        - docker
#      env:
#        - DOCKER_COMPOSE_VERSION=1.21.2
#      install:
#        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#        - sudo apt-get update
#        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#        - sudo rm /usr/local/bin/docker-compose
#        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#        - chmod +x docker-compose
#        - sudo mv docker-compose /usr/local/bin
#      before_script: make build_ci
#      script:
##        - make docker-compose && make docker-compose-down && make docker-compose DAPP=paracross && make docker-compose-down DAPP=paracross && make docker-compose DAPP=relay && make docker-compose-down DAPP=relay
#        - make docker-compose DAPP=all && make docker-compose-down DAPP=all && make clean
env:
  global:
#  - secure: Dqoa7D1nav3x0vZ7SZlmgbLbmfLe08jBBE8i/wKFruWO56lKV48zfvosAdSiAkOwR87Wco8k5ip2pjf61D9RugW47q31EPDyRTfqINcEzdAl+hHap7DbInYeQhWTw6Zf/EVRD9CYf5AIGiHgxHz1dyP3cLB+loxxRkS9AYnajd11n2EiR53UKtZAWoXYpRHWcw9lU2O/Rtj566wo6UNwGrUDuYTPRrCQ9OM8hqMHO3VyucazDDxwH+pT7xwozXfRnVTI3ObQ/8yZoxZn3mRzw8zajM0KKYx0gJnf72ZWX4LxtS4sUwnX1S7mPDmj51KkQnenf5Kn4ppdVvZZdnfPL55zQUApYBrwLGYaZsTZNXFFital83OxGp3RlhZ2jx3k6nXuxw4tV7HhKPALCe9kmiw3CU9FZ8tlTqGSb7wUNnOE0ayMMPn9Dd2GSjae60rp/TIYd9PYQIIu+FMqDbJOPLs4D6my1PKcgZ9mkwvclLxx57CR05oYb3QRl7Akll3vHbmhG5xLbde+7VnaO9q0IEs3dbGRgqKtx8+nc06wJ6UEY3GFUdTjVzHBQ4oHjQDqivhm78pjpNmtn2fO0BSS+IPX0vvMmsz5E5emUl18IgPtrRhRnEpi8WbowAv5AX0w7bq+kRdcSmJpNUIQugmq7rc9KwDkACC4U2jpNHYchCA=
#  - secure: ItFzLm1UfbY1RQtd14rLnWv8E1JnkJMCCIu7U13HZg1aAuWoKkm5WH5o4y7tLtz/f2jbee5V4LR8mpXU3Cer6MqNU8VBtsNqJIYUPpqAesMOvTpgh2r9Xddj21CfAY/VLj+yLnjXvCEWk5duY0QWO0LdGVZx7V/LBphuew79Vvg4tp99tqR2+eHlFkhwt6fbDJdHPLB22Gw+OTr/038FLIesBNyW7L99TF49fnQZGaS22j9PBmudgokTFe53QxOv/Ndq6PdQcTnU5PFJPMwazXaYtp1j3wHyRlnWHSwJbHTmsEI8YFlL2eo5FKt1uBtHcDnPm5gGK3ttDWWlHTkjaLx3yTFOJeYk07o2bKZTiVpLsY3RxhF+zn0FLtyJccZsmfY1OEqIMXar8wM8qdEI3BWMVH6kJMKOFAOxmSaiTPp2u4xTQvXP+lB4OD5NSF63SDdN54+52NogWP1rSvJsB9uS78N+Ur8K2fCIxk89+oNS65xjs3IAR1ZIP4s1coMCyQl166/GUuUGIesqjvaiO6W3AMAy8omVSYkf6qhg3O7F1wYX6/CJ3tZK92hR2DDRkaZwVNFUTKbwX9HA9Bnd0wLBFRNIjq5yEd/uEXBTXPwl/Bym/OGNilfbuK1jvlyx0Rr7g5RLCoRVycUIfrUOzWpbrjPuUbGtIEKOt+uLNXo=
  - secure: IjFjd0RRt5F+Zci7hGcrceFaajhh6sicQOqmHXceQGvS2zYNZ6C9O8xHz+ty/w6Ok3mJEb/HUVzTp2aKCQr7w4CBeHCbGBJsA1g7u9WK4zis+JEEs66CK4kJvwzWZyDSdhW8RRYP7K9TA8MXTTXEggJgBBl0urj+CA4/bc227ZiH1sD5h27DV2hFyYqIbg8qtgrWiOLDvfQJKY6ZxR9x1wHDpXQupr02AJOUMJMSGjpPvVlNj3TewHVblUn52DBDTUuNFJIMrh5AjNR/nSEnwG7v8YqvIbE4NHUK+mjhLktMmFBsm/Z5npqRYa+YIDih7aKD6aDmJ9iZBx6m1PrBWaygWTmOpV4mee8lJRygM5QRTbVBquIiBECuuGW1gyA/FrC+6wTKda2seehV2aWWMPc6sYXjvifDsoXOsV02ZO1E9+mhhDgz8W1hHxVzBTVkYWpqzir8Wstec1QZ6sOA5N/ndCLlGOi1rWcm6XlzEo8BDV8G3sOI8YsDK8PB2rPsd7MRkMKuoQe9eYsLz4KQyKv1WGBC/FCUeD9tHeZR9YWk/kr0g6Mjk4Ze/HESygTFSs57010o1Ce5dibrSV84oqQJl14A6rLPGzC8z0WaEze9QIjO4huveON+8eDtHo4uWveMQZ6qlAaVu212M96i5M+XemS8Vr+OcnyHKDz9Vbw=
